package com.saurabh.trainingmanagementsystem.Views;

public enum MenuOptions {
    DASHBOARD, ADD_CLASS, VIEW_CLASS, ADD_COURSE, VIEW_COURSE, ADD_STUDENT, VIEW_STUDENT, CHANGE_PASSWORD,
    MARK_ATTENDANCE, VIEW_ATTENDANCE, PAYMENT, PAYMENT_HISTORY, ADD_INCOME, ADD_EXPENSE, SUMMARY, LOGOUT
}
